name: sync-golang

on:
  push:
    branches: [ golang ]
    
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [ concourse ]
        
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: merge
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Branch Sync Bot"

          git merge origin/master -m "sync with golang"
          git push
