name: sync-golang

on:
  push:
    branches: [ golang ]
    
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [ concourse ]
        
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: merge
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Action"

          git merge origin/master -m "sync with golang"

      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ matrix.branch }}
