name: sync-master

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [golang]
        
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: merge
        run: |
          git merge master
          git push
